### ISSUE TITLE
Does not work in IE11

### ISSUE THREAD

**Issue by tomdohnal** [ljharb/document.contains#11]
It doesn't seem to work for me in IE11.

The problem is that the `contains` method cannot be called on an instance that doesn't implement it. In IE11, where `document.contains` is not defined but `document.body.contains` is defined, we need to `.bind(document.body)` to the `document.contains` polyfill.

**Comment by ljharb** [comment]
Unfortunately your PR would break a great many things.

Can you elaborate on what's not working in IE 11? It'd be great if you provided repro code.

**Comment by tomdohnal** [comment]
I put together a reproduction at https://github.com/tomdohnal/document-contains-error.

In `src/index.js` there is this code
```javascript
require("document.contains/auto");

var element = document.getElementById("app");

console.log(document.contains(element));
```
which logs out `true` in modern browsers but *fails* in IE 11.

You can compile it running `yarn webpack` and then either open the `index.html` file directly in IE 11 or use `yarn webpack-dev-server --host=0.0.0.0` and open it on another machine with IE 11 installed

**Comment by ljharb** [comment]
index.html points to `dist/main.js` which doesn't exist.

**Comment by ljharb** [comment]
I ran `npx browserify src/index.js > dist/main.js` and was able to get the repro going.

**Comment by ljharb** [comment]
issue 11 fixes ie 11, lol

Thanks! will be released shortly.

**Comment by ljharb** [comment]
v1.0.2 is out.

**Comment by tomdohnal** [comment]
> index.html points to `dist/main.js` which doesn't exist.

Running `yarn webpack` didn't do the job for you? Sorry about that but thanks a lot for the fix!

**Comment by ljharb** [comment]
nope, it didn't, but no worries, the repro helped :-)
